[profile.default]
verbosity = 0
optimizer = true     # enable or disable the solc optimizer
optimizer_runs = 100000 # the number of optimizer runs
solc_version = '0.8.15'
fs_permissions = [{access = "write", path = "./bytecode/"}]

remappings = [
    'src/=src/',
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
    'clones/=lib/clones-with-immutable-args/src/',
    'prb-math/=lib/prb-math/src/'   
]
[fuzz]
runs = 256